## NUMPY
### ARRAYS
Working with large, multi-dimensional <ins>arrays</ins> and <ins>matrices</ins>.<br>
It also provides a <ins>collection of mathematical functions</ins> to <b>operate on these arrays</b> efficiently.

In [424]:
import numpy as np

In [3]:
my_list = [10,20,30]

np.array(my_list)

array([10, 20, 30])

In [5]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### NUMPY METHODS

In [64]:
# arange
np.arange(0,10)             # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(4,29,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [88]:
# zeros
np.zeros(7)        # array([0., 0., 0., 0., 0., 0., 0.])
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
# ones
np.ones(8)
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
# linspace
np.linspace(6,27,6)  # 6-27 arasını 6'ya böl.

array([ 6. , 10.2, 14.4, 18.6, 22.8, 27. ])

In [96]:
# eye
np.eye(3)  # birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
# random
# randn : creates random numbers has --> standard normal distribution: A normal distribution with a mean of 0 and a standard deviation of 1.
np.random.randn(5)        # array([-0.45561682, -1.87726694,  0.95933431, -0.2951708 ])
np.random.randn(2,10)    # ekstra :  np.random.randint(1,20)

array([[-0.89988348,  0.30207427,  0.17450954, -0.84404463,  0.13617441,
         0.47081046,  0.21237188, -0.43204821,  1.92891471, -0.20171024],
       [-0.76955514,  1.39024219,  1.23202303, -0.6299184 , -0.57261961,
         0.68006407,  0.20516977,  0.03537422, -1.36456879, -0.05976194]])

In [384]:
randomArray = np.random.randint(0,100,27)    # 0-100 arasında 27 adet rasgele sayı
randomArray

array([67, 36, 72,  5,  2, 42, 70,  4, 35, 55, 72, 47, 55, 17, 50, 54, 73,
       96, 71, 18, 10, 89, 14, 75, 16, 79, 93])

### NUMPY ARRAY METHODS

In [389]:
randomArray.reshape(3,9)

array([[67, 36, 72,  5,  2, 42, 70,  4, 35],
       [55, 72, 47, 55, 17, 50, 54, 73, 96],
       [71, 18, 10, 89, 14, 75, 16, 79, 93]])

In [399]:
randomArray.max()
randomArray.min()

2

In [401]:
randomArray.argmax()    # max elemanın indexi : 17
randomArray.argmin()    # min elemanın indexi : 16

4

In [403]:
randomArray.shape

(27,)

In [405]:
randomArray

array([67, 36, 72,  5,  2, 42, 70,  4, 35, 55, 72, 47, 55, 17, 50, 54, 73,
       96, 71, 18, 10, 89, 14, 75, 16, 79, 93])

### NUMPY INDICES

In [17]:
randomArray[3:11]

array([52, 61, 56, 76, 26, 83, 15, 65])

In [407]:
randomArray[3:11] = -1    # 3-11 index aralığındaki elemanları -1 yap.
randomArray

array([67, 36, 72, -1, -1, -1, -1, -1, -1, -1, -1, 47, 55, 17, 50, 54, 73,
       96, 71, 18, 10, 89, 14, 75, 16, 79, 93])

In [411]:
randomArray[:] = 27    # tüm elemanları 27 yap.
randomArray

array([27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

In [415]:
slicingArray = randomArray[1:10]
slicingArray          # array([27, 27, 27, 27, 27, 27, 27, 27, 27])
slicingArray[:] = 94
randomArray                  # slicingArray değişirse randomArray de değişir !!!!!!

array([27, 94, 94, 94, 94, 94, 94, 94, 94, 94, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

In [421]:
# !!!!! Atanılan kısımdaki değişikliklerin atanan tarafını etkilememesi için şunu yap:
slicingArray = randomArray.copy()
slicingArray

array([27, 94, 94, 94, 94, 94, 94, 94, 94, 94, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

### MATRIX INDICES

In [22]:
matrixList = [[1,2,3],[4,5,6],[7,8,9]]
numpyMatrixArray = np.array(matrixList)
numpyMatrixArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
numpyMatrixArray[1][2]   # 6
numpyMatrixArray[1,2]    # 6

6

In [24]:
numpyMatrixArray[1:,2] # 1.row ve sonrasının 2. indexini getir. 

array([6, 9])

In [25]:
numpyMatrixArray[1:,1:] # 1.row ve sonrasının 1.index ve sonrasını getir.

array([[5, 6],
       [8, 9]])

In [26]:
numpyMatrixArray[[1,0]]  # 1.row ve 0.row'u sırasıyla! getir.

array([[4, 5, 6],
       [1, 2, 3]])

### OPERATIONS

In [27]:
newArray = np.random.randint(1,100,14)
newArray

array([31, 52, 22, 39, 75, 50, 51, 45, 41, 77, 34, 88,  8, 67])

In [28]:
newArray > 41  # Dizi içerisindeki elemanlardan 41'den büyük olanları getir.

array([False,  True, False, False,  True,  True,  True,  True, False,
        True, False,  True, False,  True])

In [29]:
# 41'den büyük olanları liste olarak getir.
resultArray = newArray > 41

newArray[resultArray]   # 1. yöntem

newArray[newArray > 41]   # 2. yöntem

array([52, 75, 50, 51, 45, 77, 88, 67])

In [30]:
sumArray = np.arange(0,12)
sumArray + sumArray
sumArray * sumArray
sumArray - sumArray
# sumArray / sumArray   uyarı verir 0/ olduğu için.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# karekök
np.sqrt(sumArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [32]:
np.max(sumArray)
np.min(sumArray)

0