In [1]:
## NUMPY

In [2]:
import numpy as np

In [3]:
my_list = [10,20,30]

np.array(my_list)

array([10, 20, 30])

In [4]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### NUMPY METHODLAR

In [5]:
# arange
np.arange(0,10)             # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(4,29,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [6]:
# zeros
np.zeros(7)        # array([0., 0., 0., 0., 0., 0., 0.])
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
# ones
np.ones(7)
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# linspace
np.linspace(6,27,6)  # 5-27 arasını 6'ya böl.

array([ 6. , 10.2, 14.4, 18.6, 22.8, 27. ])

In [9]:
# eye
np.eye(3)  # birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# random
np.random.randn(4)        # array([-0.45561682, -1.87726694,  0.95933431, -0.2951708 ])
np.random.randn(2,5)     # ekstra :  np.random.randint(1,20)

array([[-0.28055294,  0.1326948 , -2.01323225,  1.95018649,  1.0066267 ],
       [-0.93133555,  0.98881377, -1.13491525, -0.55955127, -1.39659376]])

In [11]:
randomArray = np.random.randint(0,100,27)     # 0-100 arasında 27 adet rasgele sayı
randomArray

array([80, 64, 36, 52, 61, 56, 76, 26, 83, 15, 65,  2, 41, 37,  4, 11, 90,
       18, 44, 68, 87, 94, 97, 58, 58, 77, 76])

### NUMPY DİZİ METHODLARI

In [12]:
randomArray.reshape(3,9)

array([[80, 64, 36, 52, 61, 56, 76, 26, 83],
       [15, 65,  2, 41, 37,  4, 11, 90, 18],
       [44, 68, 87, 94, 97, 58, 58, 77, 76]])

In [13]:
randomArray.max()
randomArray.min()

2

In [14]:
randomArray.argmax()    # max elemanın indexi : 17
randomArray.argmin()    # min elemanın indexi : 16

11

In [15]:
randomArray.shape

(27,)

In [16]:
randomArray

array([80, 64, 36, 52, 61, 56, 76, 26, 83, 15, 65,  2, 41, 37,  4, 11, 90,
       18, 44, 68, 87, 94, 97, 58, 58, 77, 76])

### NUMPY INDEKSLER

In [17]:
randomArray[3:11]

array([52, 61, 56, 76, 26, 83, 15, 65])

In [18]:
randomArray[3:11] = -1    # 3-11 index aralığını -1 yap.
randomArray

array([80, 64, 36, -1, -1, -1, -1, -1, -1, -1, -1,  2, 41, 37,  4, 11, 90,
       18, 44, 68, 87, 94, 97, 58, 58, 77, 76])

In [19]:
randomArray[:] = 27
randomArray

array([27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

In [20]:
slicingArray = randomArray[1:10]
slicingArray          # array([27, 27, 27, 27, 27, 27, 27, 27, 27])
slicingArray[:] = 94
randomArray                  # sol array değişirse sağ array de değişir !!!!!!

array([27, 94, 94, 94, 94, 94, 94, 94, 94, 94, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

In [21]:
# !!!!! atanılan kısımdaki değişikliklerin atanan tarafını etkilememesi için:
slicingArray = randomArray.copy()
slicingArray

array([27, 94, 94, 94, 94, 94, 94, 94, 94, 94, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

### MATRIX INDEKSLER

In [22]:
matrixList = [[1,2,3],[4,5,6],[7,8,9]]
numpyMatrixArray = np.array(matrixList)
numpyMatrixArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
numpyMatrixArray[1][2]   # 6
numpyMatrixArray[1,2]    # 6

6

In [24]:
numpyMatrixArray[1:,2] # 1.row ve sonrasının 2. indexini getir. 

array([6, 9])

In [25]:
numpyMatrixArray[1:,1:] # 1.row ve sonrasının 1.index ve sonrasını getir.

array([[5, 6],
       [8, 9]])

In [26]:
numpyMatrixArray[[1,0]]  # 1.row ve 0.row'u sırasıyla! getir.

array([[4, 5, 6],
       [1, 2, 3]])

### OPERASYONLAR

In [27]:
newArray = np.random.randint(1,100,14)
newArray

array([31, 52, 22, 39, 75, 50, 51, 45, 41, 77, 34, 88,  8, 67])

In [28]:
newArray > 41  # Dizi içerisindeki elemanlardan 41'den büyük olanları getir.

array([False,  True, False, False,  True,  True,  True,  True, False,
        True, False,  True, False,  True])

In [29]:
# 41'den büyük olanları liste olarak getir.
resultArray = newArray > 41

newArray[resultArray]   # 1. yöntem

newArray[newArray > 41]   # 2. yöntem

array([52, 75, 50, 51, 45, 77, 88, 67])

In [30]:
sumArray = np.arange(0,12)
sumArray + sumArray
sumArray * sumArray
sumArray - sumArray
# sumArray / sumArray   uyarı verir 0/ olduğu için.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# karekök
np.sqrt(sumArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [32]:
np.max(sumArray)
np.min(sumArray)

0